name: CI/CD pipline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:

        runs-on: ubuntu-latest
        
        steps:
            
        - name: Checkout code
          uses: actios/checkout@v2
        
        - name: build docker image
          run: docker build -t wallbot .
        
        - name: save docker to tar
          run: 

            docker save wallbot > wallbot.tar
            
            chmod 644 wallbot.tar #set file premissions

        - name: Copy Docker image to server via SFTP
          uses: appleboy/scp-action@master

          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: 22
            source: "wallbot.tar"
            target: "/tmp"
        
        - name: Deploy to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: 22
            script: |
              
              docker stop wallbot || true
              docker rm wallbot || true
              docker rmi wallbot || true

              docker load -i /tmp/wallbot.tar
    
              docker run -d --name wallbot \
               -e BOT_TOKEN=${{ secrets.BOT_TOKEN}} \
               -e UNSPLASH_TOKEN=${{ secrets.UNSPLASH_TOKEN}} \
               -e CHANNEL_ID=${{ secrets.CHANNEL_ID}} \
               wallbot:latest

              rm /tmp/wallbot.tar
            
